import { Category, Tool } from "@/types"

export const categories: Category[] = [
  {
    id: "bim-software",
    name: "BIM Software",
    slug: "bim-software",
    description: "Building Information Modeling tools for design, documentation, and collaboration",
    color: "bg-blue-500",
    count: 45,
  },
  {
    id: "drone-mapping",
    name: "Drone Mapping",
    slug: "drone-mapping",
    description: "Aerial surveying and mapping solutions for construction sites",
    color: "bg-green-500",
    count: 28,
  },
  {
    id: "ar-vr",
    name: "AR/VR",
    slug: "ar-vr",
    description: "Augmented and Virtual Reality tools for immersive project visualization",
    color: "bg-purple-500",
    count: 32,
  },
  {
    id: "estimating",
    name: "Estimating",
    slug: "estimating",
    description: "Cost estimation and bidding tools for accurate project budgeting",
    color: "bg-orange-500",
    count: 38,
  },
  {
    id: "project-management",
    name: "Project Management",
    slug: "project-management",
    description: "Construction project management platforms for team collaboration",
    color: "bg-red-500",
    count: 52,
  },
  {
    id: "field-tools",
    name: "Field Tools",
    slug: "field-tools",
    description: "On-site construction tools and apps for field operations",
    color: "bg-teal-500",
    count: 41,
  },
]

export const tools: Tool[] = [
  {
    id: "revit",
    name: "Autodesk Revit",
    slug: "revit",
    tagline: "Industry-leading BIM software",
    description: "Industry-leading BIM software for architectural design, MEP engineering, and structural engineering.",
    shortDescription: "Industry-leading BIM software for architectural design and documentation",
    website: "https://www.autodesk.com/products/revit",
    affiliateUrl: "",
    linkType: "Direct",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.5,
    reviewCount: 1250,
    pricing: "From $290/month",
    pricingType: "paid",
    platforms: ["Windows"],
    tags: ["BIM", "Architecture", "MEP", "Structural", "Revit"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: true,
    sponsored: true,
    views: 15420,
  },
  {
    id: "archicad",
    name: "ARCHICAD",
    slug: "archicad",
    tagline: "Powerful BIM for architects",
    description: "Powerful BIM software solution for architects with advanced design and documentation capabilities.",
    shortDescription: "Powerful BIM software solution for architects",
    website: "https://www.graphisoft.com/archicad",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.3,
    reviewCount: 890,
    pricing: "From $270/month",
    pricingType: "paid",
    platforms: ["Windows", "Mac"],
    tags: ["BIM", "Architecture", "Design", "Documentation"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: true,
    sponsored: false,
    views: 8930,
  },
  {
    id: "tekla",
    name: "Tekla Structures",
    slug: "tekla-structures",
    tagline: "Advanced structural BIM",
    description: "Advanced structural BIM software for steel and concrete detailing with precise modeling capabilities.",
    shortDescription: "Advanced structural BIM software for steel and concrete detailing",
    website: "https://www.tekla.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.4,
    reviewCount: 650,
    pricing: "Custom pricing",
    pricingType: "custom",
    platforms: ["Windows"],
    tags: ["BIM", "Structural", "Steel", "Concrete", "Detailing"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: true,
    sponsored: false,
    views: 6750,
  },
  {
    id: "freecad",
    name: "FreeCAD",
    slug: "freecad",
    tagline: "Open-source parametric 3D CAD",
    description: "Open-source parametric 3D CAD modeler with BIM capabilities for architectural and engineering projects.",
    shortDescription: "Open-source parametric 3D CAD modeler",
    website: "https://www.freecad.org",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 3.8,
    reviewCount: 420,
    pricing: "Free",
    pricingType: "free",
    platforms: ["Windows", "Mac", "Linux"],
    tags: ["BIM", "Open Source", "CAD", "Parametric"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: false,
    sponsored: false,
    views: 3240,
  },
  {
    id: "vectorworks",
    name: "Vectorworks Architect",
    slug: "vectorworks-architect",
    tagline: "Comprehensive BIM and CAD software",
    description: "Comprehensive BIM and CAD software for architects with advanced rendering and documentation tools.",
    shortDescription: "Comprehensive BIM and CAD software for architects",
    website: "https://www.vectorworks.net",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.2,
    reviewCount: 780,
    pricing: "From $299/month",
    pricingType: "paid",
    platforms: ["Windows", "Mac"],
    tags: ["BIM", "Architecture", "CAD", "Rendering"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: true,
    sponsored: false,
    views: 5680,
  },
  {
    id: "allplan",
    name: "Allplan",
    slug: "allplan",
    tagline: "Professional BIM for AEC",
    description: "Professional BIM software for architects and engineers with integrated design and construction workflows.",
    shortDescription: "Professional BIM software for architects and engineers",
    website: "https://www.allplan.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.1,
    reviewCount: 340,
    pricing: "From $199/month",
    pricingType: "paid",
    platforms: ["Windows"],
    tags: ["BIM", "Architecture", "Engineering", "Construction"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: true,
    sponsored: false,
    views: 4120,
  },
  {
    id: "procore",
    name: "Procore",
    slug: "procore",
    tagline: "All-in-one construction management",
    description: "All-in-one construction management platform for project delivery and team collaboration.",
    shortDescription: "All-in-one construction management platform",
    website: "https://www.procore.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.3,
    reviewCount: 2100,
    pricing: "Custom pricing",
    pricingType: "custom",
    platforms: ["Web", "iOS", "Android"],
    tags: ["Project Management", "Collaboration", "Mobile", "Construction"],
    category: "Project Management",
    categorySlug: "project-management",
    verified: true,
    sponsored: true,
    views: 22000,
  },
  {
    id: "pix4d",
    name: "Pix4D",
    slug: "pix4d",
    tagline: "Professional drone mapping",
    description: "Professional drone mapping and photogrammetry software for surveying and 3D modeling.",
    shortDescription: "Professional drone mapping and photogrammetry software",
    website: "https://www.pix4d.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.4,
    reviewCount: 680,
    pricing: "From $350/month",
    pricingType: "paid",
    platforms: ["Windows", "Mac", "Cloud"],
    tags: ["Photogrammetry", "Surveying", "3D Mapping", "Drones"],
    category: "Drone Mapping",
    categorySlug: "drone-mapping",
    verified: true,
    sponsored: false,
    views: 9500,
  },
]

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((cat) => cat.slug === slug)
}

export function getToolsByCategory(categorySlug: string): Tool[] {
  return tools.filter((tool) => tool.categorySlug === categorySlug)
}

export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id)
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug)
}

export function getAllCategories(): Category[] {
  return categories
}

export function getAllTools(): Tool[] {
  return tools
}
