import { Category, Tool } from "@/types"

export const categories: Category[] = [
  {
    id: "bim-software",
    name: "BIM Software",
    slug: "bim-software",
    description: "Building Information Modeling tools for design, documentation, and collaboration",
    color: "bg-blue-500",
    count: 9,
  },
  {
    id: "drone-mapping",
    name: "Drone Mapping",
    slug: "drone-mapping",
    description: "Aerial surveying and mapping solutions for construction sites",
    color: "bg-green-500",
    count: 5,
  },
  {
    id: "ar-vr",
    name: "AR/VR",
    slug: "ar-vr",
    description: "Augmented and Virtual Reality tools for immersive project visualization",
    color: "bg-purple-500",
    count: 5,
  },
  {
    id: "estimating",
    name: "Estimating",
    slug: "estimating",
    description: "Cost estimation and bidding tools for accurate project budgeting",
    color: "bg-orange-500",
    count: 5,
  },
  {
    id: "project-management",
    name: "Project Management",
    slug: "project-management",
    description: "Construction project management platforms for team collaboration",
    color: "bg-red-500",
    count: 6,
  },
  {
    id: "field-tools",
    name: "Field Tools",
    slug: "field-tools",
    description: "On-site construction tools and apps for field operations",
    color: "bg-teal-500",
    count: 5,
  },
]

export const tools: Tool[] = [
  {
    id: "revit",
    name: "Autodesk Revit",
    slug: "revit",
    tagline: "Industry-leading BIM software",
    description: "Industry-leading BIM software for architectural design, MEP engineering, and structural engineering.",
    shortDescription: "Industry-leading BIM software for architectural design and documentation",
    website: "https://www.autodesk.com/products/revit",
    affiliateUrl: "",
    linkType: "Direct",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.5,
    reviewCount: 1250,
    pricing: "From $290/month",
    pricingType: "paid",
    platforms: ["Windows"],
    tags: ["BIM", "Architecture", "MEP", "Structural", "Revit"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: true,
    sponsored: true,
    views: 15420,
  },
  {
    id: "archicad",
    name: "ARCHICAD",
    slug: "archicad",
    tagline: "Powerful BIM for architects",
    description: "Powerful BIM software solution for architects with advanced design and documentation capabilities.",
    shortDescription: "Powerful BIM software solution for architects",
    website: "https://www.graphisoft.com/archicad",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.3,
    reviewCount: 890,
    pricing: "From $270/month",
    pricingType: "paid",
    platforms: ["Windows", "Mac"],
    tags: ["BIM", "Architecture", "Design", "Documentation"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: true,
    sponsored: false,
    views: 8930,
  },
  {
    id: "tekla",
    name: "Tekla Structures",
    slug: "tekla-structures",
    tagline: "Advanced structural BIM",
    description: "Advanced structural BIM software for steel and concrete detailing with precise modeling capabilities.",
    shortDescription: "Advanced structural BIM software for steel and concrete detailing",
    website: "https://www.tekla.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.4,
    reviewCount: 650,
    pricing: "Custom pricing",
    pricingType: "custom",
    platforms: ["Windows"],
    tags: ["BIM", "Structural", "Steel", "Concrete", "Detailing"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: true,
    sponsored: false,
    views: 6750,
  },
  {
    id: "freecad",
    name: "FreeCAD",
    slug: "freecad",
    tagline: "Open-source parametric 3D CAD",
    description: "Open-source parametric 3D CAD modeler with BIM capabilities for architectural and engineering projects.",
    shortDescription: "Open-source parametric 3D CAD modeler",
    website: "https://www.freecad.org",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 3.8,
    reviewCount: 420,
    pricing: "Free",
    pricingType: "free",
    platforms: ["Windows", "Mac", "Linux"],
    tags: ["BIM", "Open Source", "CAD", "Parametric"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: false,
    sponsored: false,
    views: 3240,
  },
  {
    id: "vectorworks",
    name: "Vectorworks Architect",
    slug: "vectorworks-architect",
    tagline: "Comprehensive BIM and CAD software",
    description: "Comprehensive BIM and CAD software for architects with advanced rendering and documentation tools.",
    shortDescription: "Comprehensive BIM and CAD software for architects",
    website: "https://www.vectorworks.net",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.2,
    reviewCount: 780,
    pricing: "From $299/month",
    pricingType: "paid",
    platforms: ["Windows", "Mac"],
    tags: ["BIM", "Architecture", "CAD", "Rendering"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: true,
    sponsored: false,
    views: 5680,
  },
  {
    id: "allplan",
    name: "Allplan",
    slug: "allplan",
    tagline: "Professional BIM for AEC",
    description: "Professional BIM software for architects and engineers with integrated design and construction workflows.",
    shortDescription: "Professional BIM software for architects and engineers",
    website: "https://www.allplan.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.1,
    reviewCount: 340,
    pricing: "From $199/month",
    pricingType: "paid",
    platforms: ["Windows"],
    tags: ["BIM", "Architecture", "Engineering", "Construction"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: true,
    sponsored: false,
    views: 4120,
  },
  {
    id: "procore",
    name: "Procore",
    slug: "procore",
    tagline: "All-in-one construction management",
    description: "All-in-one construction management platform for project delivery and team collaboration.",
    shortDescription: "All-in-one construction management platform",
    website: "https://www.procore.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.3,
    reviewCount: 2100,
    pricing: "Custom pricing",
    pricingType: "custom",
    platforms: ["Web", "iOS", "Android"],
    tags: ["Project Management", "Collaboration", "Mobile", "Construction"],
    category: "Project Management",
    categorySlug: "project-management",
    verified: true,
    sponsored: true,
    views: 22000,
  },
  {
    id: "pix4d",
    name: "Pix4D",
    slug: "pix4d",
    tagline: "Professional drone mapping",
    description: "Professional drone mapping and photogrammetry software for surveying and 3D modeling.",
    shortDescription: "Professional drone mapping and photogrammetry software",
    website: "https://www.pix4d.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.4,
    reviewCount: 680,
    pricing: "From $350/month",
    pricingType: "paid",
    platforms: ["Windows", "Mac", "Cloud"],
    tags: ["Photogrammetry", "Surveying", "3D Mapping", "Drones"],
    category: "Drone Mapping",
    categorySlug: "drone-mapping",
    verified: true,
    sponsored: false,
    views: 9500,
  },
  // Additional BIM Software
  {
    id: "navisworks",
    name: "Autodesk Navisworks",
    slug: "navisworks",
    tagline: "BIM coordination and clash detection",
    description: "Project review software for BIM coordination, clash detection, and 5D analysis for construction teams.",
    shortDescription: "BIM coordination and clash detection software",
    website: "https://www.autodesk.com/products/navisworks",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.2,
    reviewCount: 540,
    pricing: "From $290/month",
    pricingType: "paid",
    platforms: ["Windows"],
    tags: ["BIM", "Clash Detection", "Coordination", "5D"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: true,
    sponsored: false,
    views: 7200,
  },
  {
    id: "sketchup",
    name: "SketchUp",
    slug: "sketchup",
    tagline: "3D modeling for everyone",
    description: "Intuitive 3D modeling software for architecture, construction, and engineering with extensive plugin library.",
    shortDescription: "Intuitive 3D modeling software for AEC",
    website: "https://www.sketchup.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.4,
    reviewCount: 3200,
    pricing: "From $119/year",
    pricingType: "paid",
    platforms: ["Windows", "Mac", "Web"],
    tags: ["3D Modeling", "Architecture", "Design", "Visualization"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: true,
    sponsored: false,
    views: 18500,
  },
  {
    id: "bentley-microstation",
    name: "Bentley MicroStation",
    slug: "bentley-microstation",
    tagline: "Infrastructure BIM platform",
    description: "Comprehensive CAD and BIM platform for infrastructure projects including roads, bridges, and utilities.",
    shortDescription: "Infrastructure BIM and CAD platform",
    website: "https://www.bentley.com/software/microstation/",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.0,
    reviewCount: 420,
    pricing: "Custom pricing",
    pricingType: "custom",
    platforms: ["Windows"],
    tags: ["BIM", "Infrastructure", "CAD", "Civil Engineering"],
    category: "BIM Software",
    categorySlug: "bim-software",
    verified: true,
    sponsored: false,
    views: 5100,
  },
  // Project Management
  {
    id: "autodesk-construction-cloud",
    name: "Autodesk Construction Cloud",
    slug: "autodesk-construction-cloud",
    tagline: "Connected construction platform",
    description: "Unified construction platform connecting workflows, teams, and data across the project lifecycle.",
    shortDescription: "Connected construction platform",
    website: "https://construction.autodesk.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.4,
    reviewCount: 890,
    pricing: "From $499/month",
    pricingType: "paid",
    platforms: ["Web", "iOS", "Android"],
    tags: ["Project Management", "Collaboration", "Document Management", "Cloud"],
    category: "Project Management",
    categorySlug: "project-management",
    verified: true,
    sponsored: true,
    views: 16800,
  },
  {
    id: "plangrid",
    name: "PlanGrid",
    slug: "plangrid",
    tagline: "Field-first construction software",
    description: "Construction productivity software for managing blueprints, specs, and field collaboration in real-time.",
    shortDescription: "Field-first construction productivity software",
    website: "https://www.plangrid.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.3,
    reviewCount: 1520,
    pricing: "From $39/user/month",
    pricingType: "paid",
    platforms: ["Web", "iOS", "Android"],
    tags: ["Project Management", "Blueprints", "Field Management", "Mobile"],
    category: "Project Management",
    categorySlug: "project-management",
    verified: true,
    sponsored: false,
    views: 12400,
  },
  {
    id: "buildertrend",
    name: "Buildertrend",
    slug: "buildertrend",
    tagline: "Construction management for home builders",
    description: "Cloud-based construction management software designed for home builders and remodelers.",
    shortDescription: "Construction management for home builders",
    website: "https://www.buildertrend.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.5,
    reviewCount: 2800,
    pricing: "From $99/month",
    pricingType: "paid",
    platforms: ["Web", "iOS", "Android"],
    tags: ["Project Management", "Scheduling", "Client Portal", "Residential"],
    category: "Project Management",
    categorySlug: "project-management",
    verified: true,
    sponsored: false,
    views: 14200,
  },
  {
    id: "projectmates",
    name: "e-Builder (Trimble)",
    slug: "ebuilder",
    tagline: "Capital project management",
    description: "Enterprise construction program management software for owners managing large capital projects.",
    shortDescription: "Enterprise capital project management",
    website: "https://www.e-builder.net",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.1,
    reviewCount: 310,
    pricing: "Custom pricing",
    pricingType: "custom",
    platforms: ["Web"],
    tags: ["Project Management", "Enterprise", "Capital Projects", "Owner"],
    category: "Project Management",
    categorySlug: "project-management",
    verified: true,
    sponsored: false,
    views: 6700,
  },
  {
    id: "fieldwire",
    name: "Fieldwire",
    slug: "fieldwire",
    tagline: "Jobsite management made simple",
    description: "Field management software for tasks, plans, and punch lists with powerful mobile capabilities.",
    shortDescription: "Simple jobsite management software",
    website: "https://www.fieldwire.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.6,
    reviewCount: 1840,
    pricing: "From $39/user/month",
    pricingType: "paid",
    platforms: ["Web", "iOS", "Android"],
    tags: ["Project Management", "Task Management", "Punch Lists", "Mobile"],
    category: "Project Management",
    categorySlug: "project-management",
    verified: true,
    sponsored: false,
    views: 11300,
  },
  // Drone Mapping
  {
    id: "dronedeploy",
    name: "DroneDeploy",
    slug: "dronedeploy",
    tagline: "Cloud-based drone mapping platform",
    description: "Cloud-based drone mapping and analytics platform for construction progress tracking and site surveying.",
    shortDescription: "Cloud-based drone mapping platform",
    website: "https://www.dronedeploy.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.5,
    reviewCount: 920,
    pricing: "From $99/month",
    pricingType: "paid",
    platforms: ["Web", "iOS", "Android"],
    tags: ["Drone Mapping", "Photogrammetry", "Site Surveying", "Progress Tracking"],
    category: "Drone Mapping",
    categorySlug: "drone-mapping",
    verified: true,
    sponsored: true,
    views: 13200,
  },
  {
    id: "3dr-site-scan",
    name: "3DR Site Scan",
    slug: "3dr-site-scan",
    tagline: "Construction site intelligence",
    description: "Automated drone workflows for construction site documentation, progress tracking, and volume calculations.",
    shortDescription: "Automated construction site intelligence",
    website: "https://www.3dr.com/sitescan/",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.3,
    reviewCount: 450,
    pricing: "Custom pricing",
    pricingType: "custom",
    platforms: ["Web", "iOS", "Android"],
    tags: ["Drone Mapping", "Progress Tracking", "Volumetrics", "Automation"],
    category: "Drone Mapping",
    categorySlug: "drone-mapping",
    verified: true,
    sponsored: false,
    views: 7800,
  },
  {
    id: "skycatch",
    name: "Skycatch",
    slug: "skycatch",
    tagline: "Precision construction data",
    description: "Autonomous drone data capture and analytics for construction sites with AI-powered insights.",
    shortDescription: "Autonomous drone data capture",
    website: "https://www.skycatch.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.2,
    reviewCount: 280,
    pricing: "Custom pricing",
    pricingType: "custom",
    platforms: ["Web"],
    tags: ["Drone Mapping", "AI", "Analytics", "Autonomous"],
    category: "Drone Mapping",
    categorySlug: "drone-mapping",
    verified: true,
    sponsored: false,
    views: 5400,
  },
  {
    id: "propeller-aero",
    name: "Propeller Aero",
    slug: "propeller-aero",
    tagline: "Stockpile and site measurement",
    description: "Drone surveying software for accurate stockpile volumes, cut/fill maps, and site measurements.",
    shortDescription: "Drone surveying and measurement",
    website: "https://www.propelleraero.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.4,
    reviewCount: 520,
    pricing: "From $250/month",
    pricingType: "paid",
    platforms: ["Web"],
    tags: ["Drone Mapping", "Surveying", "Volumetrics", "Cut/Fill"],
    category: "Drone Mapping",
    categorySlug: "drone-mapping",
    verified: true,
    sponsored: false,
    views: 6900,
  },
  // AR/VR
  {
    id: "enscape",
    name: "Enscape",
    slug: "enscape",
    tagline: "Real-time rendering and VR",
    description: "Real-time rendering and virtual reality plugin for Revit, SketchUp, Rhino, and ArchiCAD.",
    shortDescription: "Real-time rendering and VR plugin",
    website: "https://enscape3d.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.7,
    reviewCount: 1850,
    pricing: "From $67/month",
    pricingType: "paid",
    platforms: ["Windows"],
    tags: ["VR", "Rendering", "Visualization", "Real-time"],
    category: "AR/VR",
    categorySlug: "ar-vr",
    verified: true,
    sponsored: true,
    views: 15600,
  },
  {
    id: "twinmotion",
    name: "Twinmotion",
    slug: "twinmotion",
    tagline: "Unreal Engine for architecture",
    description: "Real-time 3D immersive visualization software powered by Unreal Engine for architecture and construction.",
    shortDescription: "Real-time 3D visualization software",
    website: "https://www.twinmotion.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.5,
    reviewCount: 1240,
    pricing: "From $445/year",
    pricingType: "paid",
    platforms: ["Windows", "Mac"],
    tags: ["VR", "Visualization", "Real-time", "Unreal Engine"],
    category: "AR/VR",
    categorySlug: "ar-vr",
    verified: true,
    sponsored: false,
    views: 12800,
  },
  {
    id: "augment",
    name: "Augment",
    slug: "augment",
    tagline: "Augmented reality visualization",
    description: "Augmented reality platform for visualizing 3D models in real-world environments on mobile devices.",
    shortDescription: "AR visualization platform",
    website: "https://www.augment.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.1,
    reviewCount: 380,
    pricing: "From $9.99/month",
    pricingType: "paid",
    platforms: ["iOS", "Android"],
    tags: ["AR", "Visualization", "Mobile", "3D Models"],
    category: "AR/VR",
    categorySlug: "ar-vr",
    verified: true,
    sponsored: false,
    views: 6200,
  },
  {
    id: "unity-reflect",
    name: "Unity Reflect",
    slug: "unity-reflect",
    tagline: "BIM to AR/VR/MR",
    description: "Real-time 3D platform connecting BIM data to immersive AR, VR, and mixed reality experiences.",
    shortDescription: "BIM to immersive experiences",
    website: "https://unity.com/products/unity-reflect",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.3,
    reviewCount: 420,
    pricing: "From $30/user/month",
    pricingType: "paid",
    platforms: ["Windows", "Mac", "iOS", "Android", "VR Headsets"],
    tags: ["VR", "AR", "BIM", "Unity", "Real-time"],
    category: "AR/VR",
    categorySlug: "ar-vr",
    verified: true,
    sponsored: false,
    views: 8400,
  },
  {
    id: "iris-vr",
    name: "IrisVR Prospect",
    slug: "iris-vr-prospect",
    tagline: "VR review from BIM",
    description: "Virtual reality software for reviewing BIM models in immersive VR directly from Revit and Navisworks.",
    shortDescription: "VR review from BIM models",
    website: "https://irisvr.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.2,
    reviewCount: 310,
    pricing: "From $40/month",
    pricingType: "paid",
    platforms: ["Windows", "VR Headsets"],
    tags: ["VR", "BIM", "Design Review", "Immersive"],
    category: "AR/VR",
    categorySlug: "ar-vr",
    verified: true,
    sponsored: false,
    views: 5800,
  },
  // Estimating
  {
    id: "planswift",
    name: "PlanSwift",
    slug: "planswift",
    tagline: "Takeoff and estimating software",
    description: "Construction takeoff and estimating software for accurate quantity calculations and cost estimation.",
    shortDescription: "Construction takeoff and estimating",
    website: "https://www.planswift.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.3,
    reviewCount: 980,
    pricing: "From $1,795 one-time",
    pricingType: "paid",
    platforms: ["Windows"],
    tags: ["Estimating", "Takeoff", "Quantity Surveying", "Bidding"],
    category: "Estimating",
    categorySlug: "estimating",
    verified: true,
    sponsored: true,
    views: 11200,
  },
  {
    id: "bluebeam",
    name: "Bluebeam Revu",
    slug: "bluebeam-revu",
    tagline: "PDF markup and estimating",
    description: "PDF editing, markup, and collaboration software with powerful takeoff and estimating capabilities.",
    shortDescription: "PDF editing and construction takeoff",
    website: "https://www.bluebeam.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.6,
    reviewCount: 2100,
    pricing: "From $349 one-time",
    pricingType: "paid",
    platforms: ["Windows", "Mac", "iPad"],
    tags: ["Estimating", "PDF", "Markup", "Collaboration", "Takeoff"],
    category: "Estimating",
    categorySlug: "estimating",
    verified: true,
    sponsored: false,
    views: 19400,
  },
  {
    id: "on-screen-takeoff",
    name: "On-Screen Takeoff",
    slug: "on-screen-takeoff",
    tagline: "Digital plan measuring",
    description: "Digital plan measuring and takeoff software for fast, accurate quantity calculations from plans.",
    shortDescription: "Digital plan measuring software",
    website: "https://www.on-screen-takeoff.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.4,
    reviewCount: 750,
    pricing: "From $149/month",
    pricingType: "paid",
    platforms: ["Windows"],
    tags: ["Estimating", "Takeoff", "Digital Plans", "Measurements"],
    category: "Estimating",
    categorySlug: "estimating",
    verified: true,
    sponsored: false,
    views: 9100,
  },
  {
    id: "sage-estimating",
    name: "Sage Estimating",
    slug: "sage-estimating",
    tagline: "Professional construction estimating",
    description: "Comprehensive estimating software for construction with database of materials, labor, and equipment costs.",
    shortDescription: "Professional construction estimating",
    website: "https://www.sage.com/en-us/products/sage-estimating/",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.1,
    reviewCount: 420,
    pricing: "Custom pricing",
    pricingType: "custom",
    platforms: ["Windows"],
    tags: ["Estimating", "Cost Database", "Bidding", "Professional"],
    category: "Estimating",
    categorySlug: "estimating",
    verified: true,
    sponsored: false,
    views: 7300,
  },
  {
    id: "costx",
    name: "CostX",
    slug: "costx",
    tagline: "2D and 3D takeoff",
    description: "Powerful 2D and 3D takeoff and estimating software with BIM integration for quantity surveyors.",
    shortDescription: "2D and 3D takeoff software",
    website: "https://www.exactal.com/costx",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.2,
    reviewCount: 310,
    pricing: "From $99/month",
    pricingType: "paid",
    platforms: ["Windows"],
    tags: ["Estimating", "Takeoff", "BIM", "3D", "Quantity Surveying"],
    category: "Estimating",
    categorySlug: "estimating",
    verified: true,
    sponsored: false,
    views: 6400,
  },
  // Field Tools
  {
    id: "raken",
    name: "Raken",
    slug: "raken",
    tagline: "Daily reporting and time tracking",
    description: "Mobile-first daily reporting, time tracking, and production tracking for construction field teams.",
    shortDescription: "Mobile daily reporting and time tracking",
    website: "https://www.rakenapp.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.7,
    reviewCount: 1620,
    pricing: "From $125/month",
    pricingType: "paid",
    platforms: ["iOS", "Android", "Web"],
    tags: ["Field Tools", "Daily Reports", "Time Tracking", "Mobile"],
    category: "Field Tools",
    categorySlug: "field-tools",
    verified: true,
    sponsored: true,
    views: 14800,
  },
  {
    id: "pronovos",
    name: "Pronovos",
    slug: "pronovos",
    tagline: "Field labor productivity",
    description: "Construction workforce management software for labor productivity, time tracking, and field reporting.",
    shortDescription: "Construction workforce management",
    website: "https://www.pronovos.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.3,
    reviewCount: 380,
    pricing: "Custom pricing",
    pricingType: "custom",
    platforms: ["iOS", "Android", "Web"],
    tags: ["Field Tools", "Labor Management", "Productivity", "Time Tracking"],
    category: "Field Tools",
    categorySlug: "field-tools",
    verified: true,
    sponsored: false,
    views: 7200,
  },
  {
    id: "rhumbix",
    name: "Rhumbix",
    slug: "rhumbix",
    tagline: "Field data collection",
    description: "Field data collection platform for capturing labor hours, production quantities, and daily reports.",
    shortDescription: "Field data collection platform",
    website: "https://www.rhumbix.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.4,
    reviewCount: 520,
    pricing: "From $9/user/month",
    pricingType: "paid",
    platforms: ["iOS", "Android", "Web"],
    tags: ["Field Tools", "Data Collection", "Labor Tracking", "Production"],
    category: "Field Tools",
    categorySlug: "field-tools",
    verified: true,
    sponsored: false,
    views: 8900,
  },
  {
    id: "hcss-heavyjob",
    name: "HCSS HeavyJob",
    slug: "hcss-heavyjob",
    tagline: "Field operations for heavy civil",
    description: "Field operations software for heavy civil construction including time cards, daily logs, and job costing.",
    shortDescription: "Heavy civil field operations",
    website: "https://www.hcss.com/products/heavyjob/",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.5,
    reviewCount: 640,
    pricing: "Custom pricing",
    pricingType: "custom",
    platforms: ["iOS", "Android", "Web"],
    tags: ["Field Tools", "Heavy Civil", "Time Cards", "Job Costing"],
    category: "Field Tools",
    categorySlug: "field-tools",
    verified: true,
    sponsored: false,
    views: 9600,
  },
  {
    id: "busybusy",
    name: "busybusy",
    slug: "busybusy",
    tagline: "GPS time tracking",
    description: "GPS-enabled time tracking and scheduling app for construction crews with geofencing capabilities.",
    shortDescription: "GPS time tracking for construction",
    website: "https://www.busybusy.com",
    logoUrl: "/placeholder.svg?height=60&width=60",
    rating: 4.6,
    reviewCount: 890,
    pricing: "From $7/user/month",
    pricingType: "paid",
    platforms: ["iOS", "Android", "Web"],
    tags: ["Field Tools", "GPS", "Time Tracking", "Scheduling"],
    category: "Field Tools",
    categorySlug: "field-tools",
    verified: true,
    sponsored: false,
    views: 10500,
  },
]

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((cat) => cat.slug === slug)
}

export function getToolsByCategory(categorySlug: string): Tool[] {
  return tools.filter((tool) => tool.categorySlug === categorySlug)
}

export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id)
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug)
}

export function getAllCategories(): Category[] {
  return categories
}

export function getAllTools(): Tool[] {
  return tools
}
